-- MySQL Script generated by MySQL Workbench
-- Fri Sep 24 01:27:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_documento` (
  `tip_id_tipo_documento` INT NOT NULL AUTO_INCREMENT,
  `tip_nombre_documento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`tip_id_tipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acudiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acudiente` (
  `acu_id_acudiente` INT NOT NULL AUTO_INCREMENT,
  `acu_numero_identificacion` INT NOT NULL,
  `acu_nombre` VARCHAR(45) NOT NULL,
  `acu_primer_apellido` VARCHAR(20) NOT NULL,
  `acu_segundo_apellido` VARCHAR(20) NULL,
  `acu_fijo` VARCHAR(15) NULL,
  `acu_movil` VARCHAR(10) NOT NULL,
  `acu_mail` VARCHAR(20) NULL,
  `acu_direccion` VARCHAR(45) NULL,
  `tipo_documento_fk_acudiente` INT NOT NULL,
  PRIMARY KEY (`acu_id_acudiente`, `tipo_documento_fk_acudiente`),
  CONSTRAINT `fk_acudiente_tipo_documento1`
    FOREIGN KEY (`tipo_documento_fk_acudiente`)
    REFERENCES `tipo_documento` (`tip_id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_acudiente_tipo_documento1_idx` ON `acudiente` (`tipo_documento_fk_acudiente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso` (
  `cur_id_curso` INT NOT NULL AUTO_INCREMENT,
  `cur_nombre_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cur_id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genero` (
  `gen_id` INT NOT NULL AUTO_INCREMENT,
  `gen_nombre_genero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`gen_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudiante` (
  `est_id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `est_numero_identificacion` VARCHAR(15) NOT NULL,
  `est_nombre` VARCHAR(45) NOT NULL,
  `est_primer_apellido` VARCHAR(20) NOT NULL,
  `est_segundo_apellido` VARCHAR(20) NULL,
  `est_direccion` TEXT NOT NULL,
  `est_movil` VARCHAR(25) NULL,
  `est_mail` VARCHAR(45) NULL,
  `curso_fk_estudiante` INT NOT NULL,
  `genero_fk_estudiante` INT NOT NULL,
  `tipo_documento_fk_estudiante` INT NOT NULL,
  `acudiente_fk_estudiante` INT NOT NULL,
  PRIMARY KEY (`est_id_estudiante`, `curso_fk_estudiante`, `genero_fk_estudiante`, `tipo_documento_fk_estudiante`, `acudiente_fk_estudiante`),
  CONSTRAINT `fk_estudiante_curso1`
    FOREIGN KEY (`curso_fk_estudiante`)
    REFERENCES `curso` (`cur_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_genero1`
    FOREIGN KEY (`genero_fk_estudiante`)
    REFERENCES `genero` (`gen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_tipo_documento1`
    FOREIGN KEY (`tipo_documento_fk_estudiante`)
    REFERENCES `tipo_documento` (`tip_id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_acudiente1`
    FOREIGN KEY (`acudiente_fk_estudiante`)
    REFERENCES `acudiente` (`acu_id_acudiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estudiante_curso1_idx` ON `estudiante` (`curso_fk_estudiante` ASC) VISIBLE;

CREATE INDEX `fk_estudiante_genero1_idx` ON `estudiante` (`genero_fk_estudiante` ASC) VISIBLE;

CREATE INDEX `fk_estudiante_tipo_documento1_idx` ON `estudiante` (`tipo_documento_fk_estudiante` ASC) VISIBLE;

CREATE INDEX `fk_estudiante_acudiente1_idx` ON `estudiante` (`acudiente_fk_estudiante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conductor` (
  `con_id_conductor` INT NOT NULL AUTO_INCREMENT,
  `con_numero_identificacion` VARCHAR(15) NOT NULL,
  `con_nombre` VARCHAR(32) NOT NULL,
  `con_primer_apellido` VARCHAR(15) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `con_segundo_apellido` VARCHAR(15) NULL,
  `con_movil` VARCHAR(25) NOT NULL,
  `con_mail` TEXT NULL,
  `tipo_documento_fk_conductor` INT NOT NULL,
  PRIMARY KEY (`con_id_conductor`, `tipo_documento_fk_conductor`),
  CONSTRAINT `fk_conductores_tipo_documento1`
    FOREIGN KEY (`tipo_documento_fk_conductor`)
    REFERENCES `tipo_documento` (`tip_id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_conductores_tipo_documento1_idx` ON `conductor` (`tipo_documento_fk_conductor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marca` (
  `mar_id` INT NOT NULL AUTO_INCREMENT,
  `mar_nombre_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mar_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehiculo` (
  `veh_id_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `veh_modelo` YEAR(5) NOT NULL,
  `veh_capacidad` INT NOT NULL,
  `vah_matricula_placa` VARCHAR(8) NOT NULL,
  `conductor_fk_vehiculo` INT NOT NULL,
  `marca_fk_vehiculo` INT NOT NULL,
  PRIMARY KEY (`veh_id_vehiculo`, `conductor_fk_vehiculo`, `marca_fk_vehiculo`),
  CONSTRAINT `fk_vehiculo_conductor1`
    FOREIGN KEY (`conductor_fk_vehiculo`)
    REFERENCES `conductor` (`con_id_conductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_marca1`
    FOREIGN KEY (`marca_fk_vehiculo`)
    REFERENCES `marca` (`mar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vehiculo_conductor1_idx` ON `vehiculo` (`conductor_fk_vehiculo` ASC) VISIBLE;

CREATE INDEX `fk_vehiculo_marca1_idx` ON `vehiculo` (`marca_fk_vehiculo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruta` (
  `ruta_id` INT NOT NULL AUTO_INCREMENT,
  `ruta_cupo_disponible` INT NULL,
  `ruta_cupo_asignado` INT NOT NULL,
  `ruta_nombre_zona` VARCHAR(45) NOT NULL,
  `estudiante_fk_ruta` INT ZEROFILL NOT NULL,
  `vehiculo_fk_ruta` INT NOT NULL,
  PRIMARY KEY (`ruta_id`, `estudiante_fk_ruta`, `vehiculo_fk_ruta`),
  CONSTRAINT `fk_ruta_estudiante1`
    FOREIGN KEY (`estudiante_fk_ruta`)
    REFERENCES `estudiante` (`est_id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ruta_vehiculo1`
    FOREIGN KEY (`vehiculo_fk_ruta`)
    REFERENCES `vehiculo` (`veh_id_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ruta_estudiante1_idx` ON `ruta` (`estudiante_fk_ruta` ASC) VISIBLE;

CREATE INDEX `fk_ruta_vehiculo1_idx` ON `ruta` (`vehiculo_fk_ruta` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
